version: '3.8'
services:
  django:
    build:
      context: ./backend
    environment:
      - DEBUG=0
    expose:
      - '8000'
    volumes:
      - media_data:/app/backend/media
    depends_on:
      - db
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./backend/staticfiles:/app/backend/staticfiles:ro
      - media_data:/app/backend/media:ro
    ports:
      - '80:80'
    depends_on:
      - django
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mycloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  media_data:
